import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <div className="flex gap-5 w-full bg-gray-400 p-5 justify-between">
          <div>
            <a href="/" className="2xl text-black font-bold">Navbar</a>
          </div>

          <div className="flex gap-5 ml-5">
            <a href="/about" className="2xl text-black font-bold">About</a>
            <a href="/profile" className="2xl text-black font-bold">Profile</a>
          </div>

        </div>

        {children}
      </body>
    </html>
  );
}
